[package]
name = "client"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
futures = "0.3.31"
thiserror = "2.0.12"